# Name of this app
service: fizzy
image: findingfocusdev/fizzy


#-- About your deployment --#

# Where to deploy fizzy
servers:
  web:
    # - 216.128.140.9  # Set your server name here
    - 155.138.210.159

# How you connect to your server
ssh:
  user: fizzyfocus # If you use a different username to SSH to your server, specify it here

# Automatic SSL
proxy: 
  ssl: true                # Set this to false if you *don't* want SSL
  host: fizzy.tashio.dev  # Set your server name here to use automatic SSL

# Your application configuration (secrets come from .kamal/secrets).
env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - KAMAL_REGISTRY_PASSWORD
    - SMTP_PORT
    - SMTP_DOMAIN
  clear:
    MAILER_FROM_ADDRESS: fizzy@.mg.tashio.dev # The email "from" address that Fizzy sends email from
    SMTP_ADDRESS: mg.tashio.dev # The SMTP server you'll use to send email
    MULTI_TENANT: false # Set to true to allow multiple accounts to sign up
    SOLID_QUEUE_IN_PUMA: true # Run background jobs in the app container


#-- General configuration --#

# Use a local registry to deploy
registry:
  server: docker.io  # Explicitly set to Docker Hub (or just remove server if default works)
  username: findingfocusdev # Your Docker Hub username (from your image name in logs)
  password:
    - KAMAL_REGISTRY_PASSWORD

# Handy aliasies for interacting with your deployment. For eaxmple: `bin/kamal console` will connect to a
# Rails console in production.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "fizzy_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64

accessories:
  db:
    image: mysql:8.0
    host: 155.138.210.159
#     # Change to 3306 to expose port to the world instead of just local network.
    port: "127.0.0.1:3306:3306"
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
        MYSQL_HOST: fizzy-db
      secret:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_PASSWORD
    files:
      - config/mysql/production.cnf:/etc/mysql/my.cnf
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/mysql
